### ISSUE TITLE
Change quantity of item in cart

### ISSUE THREAD

**Issue by adya-agrawal** [adyaagrawal/Barcode-shopping-app#3]
Currently there is no option to increase/ decrease quantity of item in cart Activity. Users can only modify quantity while adding items to cart. 
![image](https://user-images.githubusercontent.com/56762107/195016222-7efe85ab-fd72-4d71-b2ca-74e48a70d514.png)

**Comment by kucko99** [comment]
Could I resolve the issue?

**Comment by adya-agrawal** [comment]
Sure, go ahead
> Could I resolve the issue?

**Comment by kucko99** [comment]
@adyaagrawal could you please send me 2-3 QR codes of some products for testing? Thank you very much. I should have the issue completed within 2 days.

**Comment by adya-agrawal** [comment]
Here are a few QR codes:
1. 1981 novel: 9788192910901
2. DOMS notebook: 8906073773570
3. Axe deo: 8901030835902

**Comment by kucko99** [comment]
@adyaagrawal can you send me the QR code as a picture? Because with this barcode numbers you sent me it doesn't work.

**Comment by kucko99** [comment]
@adyaagrawal I wanted to make a pull request, but it says I don't have permission.

**Comment by adya-agrawal** [comment]
> @adyaagrawal can you send me the QR code as a picture? Because with this barcode numbers you sent me it doesn't work.

hey do you still need pictures?

**Comment by adya-agrawal** [comment]
> @adyaagrawal I wanted to make a pull request, but it says I don't have permission.

did you make a new branch?

**Comment by kucko99** [comment]
> > @adyaagrawal can you send me the QR code as a picture? Because with this barcode numbers you sent me it doesn't work.
> 
> hey do you still need pictures?

Yes, I still need to test functionality.

**Comment by kucko99** [comment]
> > @adyaagrawal I wanted to make a pull request, but it says I don't have permission.
> 
> did you make a new branch?

Of course, that's what I did first.

**Comment by adya-agrawal** [comment]
> > > @adyaagrawal I wanted to make a pull request, but it says I don't have permission.
> > 
> > 
> > did you make a new branch?
> 
> Of course, that's what I did first.

umm i can't see any forks?

**Comment by kucko99** [comment]
> > > > @adyaagrawal I wanted to make a pull request, but it says I don't have permission.
> > > 
> > > 
> > > did you make a new branch?
> > 
> > 
> > Of course, that's what I did first.
> 
> umm i can't see any forks?

![image](https://user-images.githubusercontent.com/63202105/203730880-1e13eed3-13f9-428a-aee4-0b8b28fc7a0a.png)

**Comment by kucko99** [comment]
> > @adyaagrawal can you send me the QR code as a picture? Because with this barcode numbers you sent me it doesn't work.
> 
> hey do you still need pictures?

Can you please send them to me? My email: **s.kucko3@gmail.com**

**Comment by adya-agrawal** [comment]
PR merged. Thank you @kucko99
